tokamak-network/trh-sdk

cli.go
readme.md
setup.sh

- `setup.sh` file for the simplified sdk installation
- Update readme file accordingly

feat: add setup.sh file and update readme accordingly

---

go.mod
pkg/constants/chain.go
pkg/stacks/thanos/block_explorer.go
pkg/stacks/thanos/bridge.go
pkg/stacks/thanos/thanos_stack.go
pkg/stacks/thanos/utils.go
pkg/types/setting.go
pkg/utils/tools.go
pkg/utils/tools_test.go
pkg/utils/utils.go

I added a feature for random generation of L2 chain ID. 
**functions**
* GenerateL2ChainId(): generates a unique L2 Chain ID and returns it.
* CheckChainIDUsage checks if the given chainID is already in use.
* getChainList(): fetches chain list data, using cache if valid.
**test functions**
* TestCheckChainIDUsage(): test function for the CheckChainIDUsage()
* TestGenerateL2ChainId(): test function for the GenerateL2ChainId()
```bash
cd ${TRH_SDK_ROOT}
go test ./...
```

Feat: Random Generation of L2 Chain ID

---

pkg/stacks/thanos/thanos_stack.go
scripts/install-devnet-packages.sh
scripts/install-foundry.sh
scripts/install-testnet-packages.sh
setup.sh

- Create scripts to install dependencies for both devnet/testnet.
⚠️: All scripts have been tested on only Linux, not Mac.

Feat: add bash scripts for dependency installation

---

scripts/install-testnet-packages.sh

Update the testnet package installation script so it can support arm64 as well in linux.

update: testnet packages for arm64 on linux

---

scripts/install-testnet-packages.sh

feat: update the terraform installation on Mac

---

scripts/install-devnet-packages.sh
scripts/install-testnet-packages.sh

feat: update xcode-select when Xcode Command Line Tools are already installed

---

Dockerfile.amd
Dockerfile.arm

Summary of changes.
- Add docker files for sdk deployment.

feat: add docker files for amd64 and arm64

---

cli.go
commands/logs.go
pkg/stacks/thanos/block_explorer.go
pkg/stacks/thanos/bridge.go
pkg/stacks/thanos/show_information.go
pkg/stacks/thanos/update_network.go

this command will print the logs with the filter to troubleshoot quickly the issue on some components
Test
```bash
./trh-sdk logs -c op-node -t
```

feat: show logs as the troubleshoot mode

---

pkg/constants/chain.go
pkg/stacks/thanos/bridge.go
pkg/stacks/thanos/input.go
pkg/stacks/thanos/thanos_stack.go
pkg/stacks/thanos/update_network.go
pkg/stacks/thanos/utils.go
pkg/types/op_bridge_config.go
pkg/types/setting.go

Run the deploy-contracts command:
```bash
./trh-sdk deploy-contracts --network testnet --stack thanos
```
Prompt: 
The final result:
Setting.json config:

feat: add chain configuration

---

pkg/stacks/thanos/utils.go

feat: estimate the deploy gas by 2x

---

commands/contracts.go
pkg/stacks/thanos/input.go
pkg/stacks/thanos/thanos_stack.go
pkg/types/setting.go

Deploying in the first time and canceling in the middle of this process:
[deploy_thanos_thanos_testnet_1746331391.log](https://github.com/user-attachments/files/20026118/deploy_thanos_thanos_testnet_1746331391.log)
Redeploying again:
[deploy_thanos_thanos_testnet_1746332070.log](https://github.com/user-attachments/files/20026119/deploy_thanos_thanos_testnet_1746332070.log)
Screenshot:

feat: resume deploying L1 contracts

---

pkg/stacks/thanos/thanos_stack.go

This PR is for resolving issue #55
```bash
Admin account balance: 16.94 ETH
⛽ Current gas price: 73.3002 Gwei
💰 Estimated deployment cost: 11.7280 ETH
✅ The admin account has sufficient balance to proceed with deployment.
🔎 The SDK is ready to deploy the contracts to the L1 network. Do you want to proceed(Y/n)?
```

Feat: check admin balance before deployment

---

pkg/stacks/thanos/thanos_stack.go

chore: add deploy successfully message

---

pkg/stacks/thanos/block_explorer.go
pkg/stacks/thanos/update_network.go

fix(block-explorer): upgrade wrong helm release when updating the network configuration

---

pkg/cloud-provider/aws/aws.go
pkg/stacks/thanos/input.go
pkg/utils/aws.go

https://github.com/tokamak-network/trh-sdk/issues/71

feat: add aws region validation logic

---

pkg/utils/helm.go

Remove the pvc status checking step since it is useless.

chore: remove pvc check after infra deployment

---

scripts/install-devnet-packages.sh
scripts/install-foundry.sh
scripts/install-testnet-packages.sh
setup.sh

Described to https://github.com/tokamak-network/trh-sdk/issues/79

add to check current shell before installing dependencies on macOS

---

pkg/constants/chain.go
pkg/stacks/thanos/input.go

Challenge period on mainnet should be fixed to 604800. So If it is mainnet, the user cannot set it in the advanced configuration menu.

chore: fixed challenge period on mainnet

---

setup.sh

feat: remove files after setup done

---

commands/contracts.go
commands/deploy.go
commands/destroy.go
commands/logs.go
commands/plugins.go
commands/show_information.go
commands/update_network.go
pkg/stacks/thanos/aws.go
pkg/stacks/thanos/block_explorer.go
pkg/stacks/thanos/bridge.go
pkg/stacks/thanos/show_information.go
pkg/stacks/thanos/thanos_stack.go
pkg/stacks/thanos/update_network.go

feat: add DeployConfig as a property of ThanosStack struct

---

pkg/stacks/thanos/thanos_stack.go

Resolved Harvey's issue when running by oh my zsh

feat: remove login shell when making the devnet network up

---

setup.sh

It has enhanced the setup script to support multiple installation modes through command-line arguments, allowing users to install different versions of TRH SDK.
Added argument parsing logic to support:
- Default: Install latest release version
- `-c <commit_hash>` or `--commit <commit_hash>`: Install specific commit
- `--latest`: Install from main branch (latest commit)
- `-h` or `--help`: Show usage information
1. Developers or Testers can install TRH SDK of a specific commit or branch to test new features or bug fixes.
2. Shorten development cycles by pre-verifying the latest changes in the main branch before release.
3. In production environment, we can pin and use specific verified release versions, reducing risk due to unexpected changes.
```bash
./setup.sh
./setup.sh -c a1b2c3d4e5f6 …
```

Add command-line argument support to setup.sh

---

pkg/stacks/thanos/monitoring.go
pkg/stacks/thanos/thanos_stack.go

https://tokamak-network.slack.com/archives/C06UKCF86TE/p1750961774099629?thread_ts=1750958937.540829&cid=C06UKCF86TE

fix: install monitoring issues

---

pkg/constants/plugins.go
pkg/stacks/thanos/monitoring.go
pkg/stacks/thanos/thanos_stack.go
pkg/types/monitoring_config.go

Added installation & uninstallation logic of the monitoring plugin for Thanos Stack deployments. It includes Prometheus, Grafana, and blackbox exporter with pre-built dashboards and automated metric collection for all Thanos Stack components.
It provides monitoring metrics collection and dashboard visualization capabilities for k8s clusters and Thanos Stack components, helping to reduce the difficulties of L2 network operations.
* Issue: https://github.com/tokamak-network/trh-sdk/issues/49
* Dependency branch (helm chart): https://github.com/tokamak-network/tokamak-thanos-stack/tree/feat/chart-monitoring
1. Should deploy monitoring plugin on the path where we deploy L2 chain 
2. Use https://github.com/tokamak-network/tokamak-thanos-stack/tree/feat/chart-monitoring for deploying monitoring …

feat: integrate monitoring plugin

---

pkg/stacks/thanos/monitoring.go

Rename `ChainName` to `ResourceName` to prevent the confusing

refactor: rename ChainName to ResourceName in the Monitoring Config struct

---

pkg/utils/file.go
pkg/utils/utils.go

feat: random namespace by chain name

---

cli.go
commands/alert_config.go
pkg/constants/alerts.go
pkg/constants/channels.go
pkg/stacks/thanos/alert_customization.go
pkg/stacks/thanos/input.go
pkg/stacks/thanos/monitoring.go
pkg/types/monitoring_config.go
pkg/utils/kubectl.go
pkg/utils/utils.go
readme.md

Implemented a comprehensive alert customization feature that provides complete monitoring configuration capabilities for Thanos Stack-based L2 stack. It includes interactive CLI commands for managing alert rules, notification channels (email/telegram), and real-time status monitoring. 
Supported features:
* Check the alert status
* Configure and disable alert channels: email, telegram
* Configure alert rules: adjust thresholds, disable each rule, and reset to defaults
* User Guide: https://www.notion.so/tokamak/Monitoring-plugin-Guide-22bd96a400a380469c14d639a8fc5f9f?source=copy_link#234d96a400a380748d86edc9d0f5d0db
* Updated README: https://github.com/tokamak-network/trh-sdk/blob/feat/alert-customization/readme.md#alert-configuration

Feat: alert customization

---

.gitignore
cli.go
commands/plugins.go
pkg/constants/block_explorer.go
pkg/constants/cross_trade.go
pkg/constants/forge.go
pkg/constants/l2_contracts.go
pkg/constants/plugins.go
pkg/stacks/thanos/block_explorer.go
pkg/stacks/thanos/cross_trade.go
pkg/stacks/thanos/input.go

go build && ./trh-sdk install cross-trade
Output:
Recording video:
https://drive.google.com/file/d/1rYSFLZ7xFZJQ9IiL5PGhC_904PyxEkeL/view?usp=sharing

feat: add Cross trade integration

---

pkg/stacks/thanos/block_explorer.go
pkg/stacks/thanos/input.go
pkg/types/terraform.go
pkg/utils/aws.go

feat: add region env when installing block explorer
